"""Mocked Ultsys user data for find_ultsys_user()."""
# pylint: disable=too-many-lines

ULTSYS_USER_DATA = [
    {
        'id': '1',
        'city': 'Kalamazoo',
        'state': 'MI',
        'address': '1010 Goff Avenue',
        'zip': '49007',
        'firstname': 'Michael',
        'lastname': 'Albers',
        'phone': '2695351761',
        'email': 'michaelalbers@cuvox.de',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '1'
    },
    {
        'id': '2',
        'city': 'Hillsdale',
        'state': 'MI',
        'address': '4379 Elk Avenue',
        'zip': '49242',
        'firstname': 'Lisa',
        'lastname': 'Albers',
        'phone': '5174397246',
        'email': 'lisaalbers@gmail.de',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '2'
    },
    {
        'id': '3',
        'city': 'Glen Allen',
        'state': 'VA',
        'address': '1781 Melody Lane',
        'zip': '23060',
        'firstname': 'Rachel',
        'lastname': 'Albers',
        'phone': '8043999085',
        'email': 'rachelalbers@aol.de',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '3'
    },
    {
        'id': '4',
        'city': 'Lexington',
        'state': 'KY',
        'address': '1329 Meadowcrest Lane',
        'zip': '40507',
        'firstname': 'Shannon',
        'lastname': 'Albers',
        'phone': '6065092795',
        'email': 'shannonalbers@yahoo.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '4'
    },
    {
        'id': '5',
        'city': 'Farmington Hills',
        'state': 'MI',
        'address': '4370 Bombardier Way',
        'zip': '48335',
        'firstname': 'Joshua',
        'lastname': 'Albers',
        'phone': '7348723251',
        'email': 'joshuaalbers@disney.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '5'
    },
    {
        'id': '6',
        'city': 'Hurt',
        'sate': 'VA',
        'address': '4977 Worley Avenue',
        'zip': '24563',
        'firstname': 'Michael',
        'lastname': 'Astore',
        'phone': '4343247604',
        'email': 'michaelastore@dayrep.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '6'
    },
    {
        'id': '7',
        'city': 'Temple',
        'state': 'TX',
        'address': '2260 Beeghley Street',
        'zip': '76501',
        'firstname': 'Paul',
        'lastname': 'Astore',
        'phone': '2549820319',
        'email': 'paulastore@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '7'
    },
    {
        'id': '8',
        'city': 'St Robert',
        'state': 'MO',
        'address': '703 Maple Court',
        'zip': '65473',
        'firstname': 'Regenia',
        'lastname': 'Astore',
        'phone': '5733366426',
        'email': 'reginaastore@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '8'
    },
    {
        'id': '9',
        'city': 'Kanawha',
        'state': 'IA',
        'address': '629 Heavner Court',
        'zip': '50447',
        'firstname': 'Arvilla',
        'lastname': 'Astore',
        'phone': '5159344557',
        'email': 'arvillaastore@fresh.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '9'
    },
    {
        'id': '10',
        'city': 'Salt Lake City',
        'state': 'UT',
        'address': '4663 Austin Secret Lane',
        'zip': '84104',
        'firstname': 'Gerald',
        'lastname': 'Astore',
        'phone': '4355785485',
        'email': 'geraldastore@sprint.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '10'
    },
    {
        'id': '11',
        'city': 'Marlboro',
        'state': 'MA',
        'address': '3386 Hampton Meadows',
        'zip': '1752',
        'firstname': 'Viola',
        'lastname': 'Anderson',
        'phone': '9783829172',
        'email': 'violaanderson@telework.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '11'
    },
    {
        'id': '12',
        'city': 'Cambridge',
        'state': 'MA',
        'address': '1303 Tenmile Road',
        'zip': '2141',
        'firstname': 'Cora',
        'lastname': 'Anderson',
        'phone': '7817138211',
        'email': 'coraanderson@askus.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '12'
    },
    {
        'id': '13',
        'city': 'Findlay',
        'state': 'OH',
        'address': '4193 Cedarstone Drive',
        'zip': '45840',
        'firstname': 'James',
        'lastname': 'Anderson',
        'phone': '4194240416',
        'email': 'jamesanderson@appomatax.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '13'
    },
    {
        'id': '14',
        'city': 'Sherman Oaks',
        'state': 'CA',
        'address': '3939 Quiet Valley Lane',
        'zip': '91403',
        'firstname': 'Amanda',
        'lastname': 'Anderson',
        'phone': '8189069366',
        'email': 'amandaanderson@att.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '14'
    },
    {
        'id': '15',
        'city': 'Philadelphia',
        'state': 'PA',
        'address': '843 Filbert Street',
        'zip': '19107',
        'firstname': 'Lamont',
        'lastname': 'Anderson',
        'phone': '6108397265',
        'email': 'lamontanderson@disco.net',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '15'
    },
    {
        'id': '16',
        'city': 'Oakland',
        'state': 'CA',
        'address': '4238 Park Street',
        'zip': '94612',
        'firstname': 'Delores',
        'lastname': 'Adamson',
        'phone': '9253851361',
        'email': 'deloresadamson@verizon.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '16'
    },
    {
        'id': '17',
        'city': 'Seattle',
        'state': 'WA',
        'address': '3227 Ryder Avenue',
        'zip': '98161',
        'firstname': 'James',
        'lastname': 'Adamson',
        'phone': '4253108304',
        'email': 'jamesadamson@sprint.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '17'
    },
    {
        'id': '18',
        'city': 'San Jose',
        'state': 'CA',
        'address': '1072 Hide A Way Road',
        'zip': '95127',
        'firstname': 'Michelle',
        'lastname': 'Adamson',
        'phone': '4082586814',
        'email': 'michelleadamson@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '18'
    },
    {
        'id': '19',
        'city': 'Atlanta',
        'state': 'GA',
        'address': '1933 Despard Street',
        'zip': '30303',
        'firstname': 'Anna',
        'lastname': 'Adamson',
        'phone': '4046722401',
        'email': 'annaadamson@aol.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '19'
    },
    {
        'id': '20',
        'city': 'Lafayette',
        'state': 'LA',
        'address': '4939 Sarah Drive',
        'zip': '70501',
        'firstname': 'Maribel',
        'lastname': 'Adamson',
        'phone': '3374227936',
        'email': 'maribeladamson@joints.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '20'
    },
    {
        'id': '21',
        'city': 'Portland',
        'state': 'OR',
        'address': '915 New Street',
        'zip': '97205',
        'firstname': 'Leslie',
        'lastname': 'Azike',
        'phone': '5413031854',
        'email': 'leslieaziken@superrito.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '21'
    },
    {
        'id': '22',
        'city': 'Fresno',
        'state': 'CA',
        'address': '4466 Chicago Avenue',
        'zip': '93711',
        'firstname': 'Ricardo',
        'lastname': 'Azike',
        'phone': '5595572912',
        'email': 'ricardoaziken@cannoli.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '22'
    },
    {
        'id': '23',
        'city': 'Seattle',
        'state': 'WA',
        'address': '4907 Owagner Lane',
        'zip': '98155',
        'firstname': 'Jane',
        'lastname': 'Azike',
        'phone': '2063060653',
        'email': 'janeaziken@asparagus.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '23'
    },
    {
        'id': '24',
        'city': 'Purdin',
        'state': 'MO',
        'address': '55 Fairmont Avenue',
        'zip': '64674',
        'firstname': 'Angel',
        'lastname': 'Azike',
        'phone': '6602448753',
        'email': 'angelaziken@giant.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '24'
    },
    {
        'id': '25',
        'city': 'Hamer',
        'state': 'ID',
        'address': '1060 Science Center Drive',
        'zip': '83425',
        'firstname': 'Jaunita',
        'lastname': 'Azike',
        'phone': '2086626572',
        'email': 'jaunitaaziken@shoppers.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '25'
    },
    {
        'id': '26',
        'city': 'Metairie',
        'state': 'LA',
        'address': '4660 Big Indian',
        'zip': '70001',
        'firstname': 'Rick',
        'lastname': 'Bagsley',
        'phone': '5046469761',
        'email': 'rickbagsley@harrisons.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '26'
    },
    {
        'id': '27',
        'city': 'Adrian',
        'state': 'MI',
        'address': '1914 Elk Avenue',
        'zip': '49221',
        'firstname': 'Kathy',
        'lastname': 'Bagsley',
        'phone': '5175024898',
        'email': 'kathybagsley@nbc.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '27'
    },
    {
        'id': '28',
        'city': 'Cambridge',
        'state': 'MA',
        'address': '61 Metz Lane',
        'zip': '2138',
        'firstname': 'Rebecca',
        'lastname': 'Bagsley',
        'phone': '8572288002',
        'email': 'rebeccabagsley@msn.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '28'
    },
    {
        'id': '29',
        'city': 'Philadelphia',
        'state': 'PA',
        'address': '2663 Garrett Street',
        'zip': '70001',
        'firstname': 'Charles',
        'lastname': 'Bagsley',
        'phone': '2679365283',
        'email': 'charlesbagsley@yahoo.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '29'
    },
    {
        'id': '30',
        'city': 'Hilliard',
        'state': 'OH',
        'address': '2495 Collins Avenue',
        'zip': '43026',
        'firstname': 'Sharon',
        'lastname': 'Bagsley',
        'phone': '6147874459',
        'email': 'sharonbagsley@aol.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '30'
    },
    {
        'id': '31',
        'city': 'Dayton',
        'state': 'OH',
        'address': '2984 Harter Street',
        'zip': '45407',
        'firstname': 'Blanche',
        'lastname': 'Brittone',
        'phone': '9376340489',
        'email': 'blanchebrittone@msn.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '31'
    },
    {
        'id': '32',
        'city': 'Winchester',
        'state': 'KY',
        'address': '1745 Black Stallion Road',
        'zip': '40391',
        'firstname': 'Matthew',
        'lastname': 'Brittone',
        'phone': '8595820397',
        'email': 'matthewbrittone@yahoo.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '32'
    },
    {
        'id': '33',
        'city': 'Chicago',
        'state': 'IL',
        'address': '2996 Virginia Street',
        'zip': '60653',
        'firstname': 'Tina',
        'lastname': 'Brittone',
        'phone': '7736241127',
        'email': 'tinabrittone@aol.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '33'
    },
    {
        'id': '34',
        'city': 'Jacksonville',
        'state': 'FL',
        'address': '4183 Boundary Street',
        'zip': '32216',
        'firstname': 'Janice',
        'lastname': 'Brittone',
        'phone': '9046359196',
        'email': 'janicebrittone@astonmartin.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '34'
    },
    {
        'id': '35',
        'city': 'Nashville',
        'state': 'TN',
        'address': '4908 Wilkinson Street',
        'zip': '37203',
        'firstname': 'Carl',
        'lastname': 'Brittone',
        'phone': '6154351535',
        'email': 'carlbrittone@navycenter.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '35'
    },
    {
        'id': '36',
        'city': 'Alpena',
        'state': 'MI',
        'address': '3625 Hart Ridge Road',
        'zip': '49707',
        'firstname': 'Noelle',
        'lastname': 'Becker',
        'phone': '9893545687',
        'email': 'noellebecker@aol.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '36'
    },
    {
        'id': '37',
        'city': 'Kettering',
        'state': 'OH',
        'address': '3046 College Avenue',
        'zip': '45429',
        'firstname': 'Amanda',
        'lastname': 'Becker',
        'phone': '9373974680',
        'email': 'amandabecker@att.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '37'
    },
    {
        'id': '38',
        'city': 'Scranton',
        'state': 'PA',
        'address': '388 Carriage Lane',
        'zip': '18503',
        'firstname': 'John',
        'lastname': 'Becker',
        'phone': '5702374887',
        'email': 'johnbecker@military.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '38'
    },
    {
        'id': '39',
        'city': 'Larkspur',
        'state': 'CA',
        'address': '859 Roosevelt Street',
        'zip': '94939',
        'firstname': 'Dana',
        'lastname': 'Becker',
        'phone': '4154643141',
        'email': 'danabecker@usagreat.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '39'
    },
    {
        'id': '40',
        'city': 'Norfolk',
        'state': 'VA',
        'address': '564 Pinchelone Street',
        'zip': '23510',
        'firstname': 'Mark',
        'lastname': 'Becker',
        'phone': '7573427244',
        'email': 'markbecker@askus.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '40'
    },
    {
        'id': '41',
        'city': 'Milwaukee',
        'state': 'WI',
        'address': '2872 Oakridge Farm Lane',
        'zip': '53202',
        'firstname': 'Lynn',
        'lastname': 'Bradley',
        'phone': '2623137387',
        'email': 'lynnbradley@durox.org',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '41'
    },
    {
        'id': '42',
        'city': 'Springfield',
        'state': 'MO',
        'address': '1865 Briarwood Road',
        'zip': '65804',
        'firstname': 'Carmen',
        'lastname': 'Bradley',
        'phone': '4178918952',
        'email': 'carmenbradley@attinit.net',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '42'
    },
    {
        'id': '43',
        'city': 'San Jose',
        'state': 'CA',
        'address': '1138 Brookview Drive',
        'zip': '95113',
        'firstname': 'Walter',
        'lastname': 'Bradley',
        'phone': '4089897683',
        'email': 'walterbradley@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '43'
    },
    {
        'id': '44',
        'city': 'Jackson',
        'state': 'MS',
        'address': '3378 Lena Lane',
        'zip': '39201',
        'firstname': 'Juana',
        'lastname': 'Bradley',
        'phone': '6014519648',
        'email': 'juanabradley@soaring.org',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '44'
    },
    {
        'id': '45',
        'city': 'Memphis',
        'state': 'TN',
        'address': '2652 Edgewood Road',
        'zip': '38110',
        'firstname': 'Donald',
        'lastname': 'Bradley',
        'phone': '9012628764',
        'email': 'donaldbradley@sinti.org',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '45'
    },









    {
        'id': '46',
        'city': 'Westbury',
        'state': 'NY',
        'address': '2151 Deans Lane',
        'zip': '11590',
        'firstname': 'Antonio',
        'lastname': 'Baker',
        'phone': '9148304107',
        'email': 'antoniobaker@packers.org',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '46'
    },
    {
        'id': '47',
        'city': 'Corinth',
        'state': 'ME',
        'address': '4381 Retreat Avenue',
        'zip': '4427',
        'firstname': 'Edward',
        'lastname': 'Baker',
        'phone': '2072853836',
        'email': 'edwardbaker@att.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '47'
    },
    {
        'id': '48',
        'city': 'Rolling Meadows',
        'state': 'IL',
        'address': '1566 Hickman Street',
        'zip': '60008',
        'firstname': 'Charlie',
        'lastname': 'Baker',
        'phone': '6305041390',
        'email': 'charliebaker@yahoo.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '48'
    },
    {
        'id': '49',
        'city': 'Independence',
        'state': 'KS',
        'address': '3641 Better Street',
        'zip': '64055',
        'firstname': 'Paul',
        'lastname': 'Baker',
        'phone': '9132405594',
        'email': 'paulbaker@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '49'
    },
    {
        'id': '50',
        'city': 'Denver',
        'state': 'CO',
        'address': '2845 Shobe Lane',
        'zip': '2845',
        'firstname': 'Danica',
        'lastname': 'Baker',
        'phone': '9704250367',
        'email': 'danicabaker@verizon.net',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '50'
    },
    {
        'id': '51',
        'city': 'Longview',
        'state': 'TX',
        'address': '359 Florence Street',
        'zip': '75601',
        'firstname': 'Regina',
        'lastname': 'Calvers',
        'phone': '9034754228',
        'email': 'reginacalvers@getty.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '51'
    },
    {
        'id': '52',
        'city': 'Ontario',
        'state': 'CA',
        'address': '1814 Gordon Street',
        'zip': '91761',
        'firstname': 'Carol',
        'lastname': 'Cooperton',
        'phone': '9095205191',
        'email': 'carolcooperton@dayrep.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '52'
    },
    {
        'id': '53',
        'city': 'Sugar Land',
        'state': 'TX',
        'address': '2910 Bird Spring Lane',
        'zip': '77487',
        'firstname': 'Amber',
        'lastname': 'Carollton',
        'phone': '2815662066',
        'email': 'ambercarollton@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '53'
    },
    {
        'id': '54',
        'city': 'Waco',
        'state': 'TX',
        'address': '1301 Sussex Court',
        'zip': '76701',
        'firstname': 'Edward',
        'lastname': 'Clark',
        'phone': '2545489021',
        'email': 'edwardclark@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '54'
    },
    {
        'id': '55',
        'city': 'Honolulu',
        'state': 'HI',
        'address': '4880 Indiana Avenue',
        'zip': '96814',
        'firstname': 'Kristy',
        'lastname': 'Carpenter',
        'phone': '8085982883',
        'email': 'kristycarpenter@aol.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '55'
    },
    {
        'id': '56',
        'city': 'Southfield',
        'state': 'MI',
        'address': '963 Reppert Coal Road',
        'zip': '48075',
        'firstname': 'Ashley',
        'lastname': 'Garland',
        'phone': '5868079782',
        'email': 'ashleygarland@yahoo.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '56'
    },
    {
        'id': '57',
        'city': 'Fort Worth',
        'state': 'TX',
        'address': '824 Sardis Sta',
        'zip': '76102',
        'firstname': 'Ruth',
        'lastname': 'Geoffrey',
        'phone': '8176230206',
        'email': 'ruthgeoffrey@msn.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '57'
    },
    {
        'id': '58',
        'city': 'New Brunswick',
        'state': 'NJ',
        'address': '302 Webster Street',
        'zip': '8901',
        'firstname': 'David',
        'lastname': 'Gaffer',
        'phone': '7326236967',
        'email': 'davidgaffer@verizon.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '58'
    },
    {
        'id': '59',
        'city': 'Hanna',
        'state': 'OK',
        'address': '2951 Camel Back Road',
        'zip': '74845',
        'firstname': 'Kisha',
        'lastname': 'Griffin',
        'phone': '9186573694',
        'email': 'kishagriffin@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '59'
    },
    {
        'id': '60',
        'city': 'Minneapolis',
        'state': 'MN',
        'address': '1081 Jewell Road',
        'zip': '55401',
        'firstname': 'Janie',
        'lastname': 'Glasser',
        'phone': '6126382947',
        'email': 'janieglasser@sprint.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '60'
    },
    {
        'id': '61',
        'city': 'Hollister',
        'state': 'CA',
        'address': '3684 Emily Renzelli Boulevard',
        'zip': '95023',
        'firstname': 'Anne',
        'lastname': 'Isaacs',
        'phone': '8316305831',
        'email': 'anneisaacs@kirkland.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '61'
    },
    {
        'id': '62',
        'city': 'Whittier',
        'state': 'CA',
        'address': '4349 Thompson Street',
        'zip': '90602',
        'firstname': 'Joel',
        'lastname': 'Ikrim',
        'phone': '5626935191',
        'email': 'joelikram@aol.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '62'
    },
    {
        'id': '63',
        'city': 'Falls Church',
        'state': 'VA',
        'address': '1499 Lawman Avenue',
        'zip': '22042',
        'firstname': 'Thomas',
        'lastname': 'Izicki',
        'phone': '7032083319',
        'email': 'thomasizicki@att.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '63'
    },
    {
        'id': '64',
        'city': 'Richmond',
        'state': 'IN',
        'address': '2418 Winifred Way',
        'zip': '47374',
        'firstname': 'Davina',
        'lastname': 'Iopren',
        'phone': '7656920921',
        'email': 'thomasizicki@gmail.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '64'
    },
    {
        'id': '65',
        'city': 'Topeka',
        'state': 'KS',
        'address': '3476 Maloy Court',
        'zip': '66608',
        'firstname': 'Vanessa',
        'lastname': 'Iodanna',
        'phone': '7854357271',
        'email': 'vanessaiodanna@hertz.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '65'
    },
    {
        'id': '66',
        'city': 'Los Angeles',
        'state': 'CA',
        'address': '533 Koontz Lane',
        'zip': '90017',
        'firstname': 'Carrie',
        'lastname': 'Lorry',
        'phone': '8188193500',
        'email': 'carriealorry@hapspell.com',
        'donation_prior_amount': '0',
        'donation_sum': '0',
        'donation_time': None,
        'uid': '66'
    }
]
